name = "JCDevCCBlade"
#uuid = "e1828068-15df-11e9-03e4-ef195ea46fa4"  #original uuid
uuid = "1882b919-6739-4615-a2f8-153f25957618" #my uuid generated following these instructions below
#(https://stackoverflow.com/questions/69945658/how-to-create-a-uuid-for-a-julia-package
authors = ["Andrew Ning <aning@byu.edu>"]
version = "0.2.3"

[deps]
FLOWMath = "6cb5d3fb-0fe8-4cc2-bd89-9fe0b19a99d3"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.3"
FLOWMath = "0.3"
